services:
  - type: web
    name: klipper-api
    env: docker
    dockerfilePath: ./Dockerfile
    rootDir: apps/klipper-api
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://klipper-app.vercel.app,https://klipper.quebec.com.br,https://www.klipper.quebec.com.br
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
