default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: klipper_development

test:
  <<: *default
  database: klipper_test
  url: <%= ENV.fetch("TEST_DATABASE_URL", "postgresql://localhost/klipper_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
